---

- name: update apt repository
  sudo: yes
  sudo_user: root
  apt: update_cache=yes

- name: Install common packages
  sudo: yes
  sudo_user: root
  apt: name={{ item }} state=present
  with_items:
      - git
      - python-pycurl

